langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RlQNvOzZfGjc/bVnoiAZ7kjI4NRJQmeea4pFrwotfWbd71nc/eNwFCAIDp8Cxi63D01+NegaQdAAKjAoIdqzTpucYDOBhZhhSN4JaAGent2bnAf/FPKL4Klfcz/qAFHlBlGBPbhcqCgV9TRaZvbd9ZIJdh4YvD8b56oVvRUx6T3IAefNooGeS4Mdpaz23zduXhKV6uhSVVhUIdlM8ZkXglHcgMQS91BgxqsMIAttFEcNe/kpJC1bs5RX/da+xsQ514cOKCEypijkgGtmDsDMQSWDyaViEKeM3+e0FvpOi37UlYMrtKNf/CMcQkxHVmi62pq0oGPVVHs5o7U9ndm+gRSNqsUBUH7QLRTfxekyeDObmli7Tvs4F50c08cJUiMLjFzNbnlIDkdksZ/EIxBaCj2TjfB225J6LGh76MeWETtHm/ZItLRg2G87xUJY9nAZ1Xq9gIbZBl4GFHq37ELz7AOkc1RZbfjKcDH3PX96p+R9+ZwO8YmMneSJsfNSqeK06OdbLoRyfhdCRnZhcdu7eMBSsSSknPX82Tj4u9YUklaBx5V4p0zcYlQt/faMncqwBUXhG/SXpLnAy2KsYFxda+ihG+HeZ4Xd/6csDLH5iJDnyJr/L9846DersjLkw9OlPny2HQeTGfg47hQe4NP5PFr4/cFSYwPStxF8ShWPcrI=
  app: 
  run: rails db:migrate
